// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Habit defines model for habit.
type Habit struct {
	Description *string `json:"description,omitempty"`
	HabitId     int     `json:"habit_id"`
	HabitName   *string `json:"habit_name,omitempty"`
}

// Habits defines model for habits.
type Habits = []Habit

// UserHabit defines model for userHabit.
type UserHabit struct {
	CurrentPlan *int                `json:"current_plan,omitempty"`
	HabitId     *int                `json:"habit_id,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
	UserId      *int                `json:"user_id,omitempty"`
}

// UserHabits defines model for userHabits.
type UserHabits = []UserHabit

// HabitId defines model for habitId.
type HabitId = int

// UserId defines model for userId.
type UserId = int

// PostHabitsJSONBody defines parameters for PostHabits.
type PostHabitsJSONBody struct {
	Description *string `json:"description,omitempty"`
	HabitName   *string `json:"habit_name,omitempty"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostUserHabitsJSONBody defines parameters for PostUserHabits.
type PostUserHabitsJSONBody struct {
	CurrentPlan int                `json:"current_plan"`
	Description *string            `json:"description,omitempty"`
	HabitName   string             `json:"habit_name"`
	StartDate   openapi_types.Date `json:"start_date"`
	UserId      int                `json:"user_id"`
}

// PutUserHabitsJSONBody defines parameters for PutUserHabits.
type PutUserHabitsJSONBody struct {
	CurrentPlan int `json:"current_plan"`
	HabitId     int `json:"habit_id"`
	UserId      int `json:"user_id"`
}

// PostHabitsJSONRequestBody defines body for PostHabits for application/json ContentType.
type PostHabitsJSONRequestBody PostHabitsJSONBody

// PutHabitsJSONRequestBody defines body for PutHabits for application/json ContentType.
type PutHabitsJSONRequestBody = Habit

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// PostUserHabitsJSONRequestBody defines body for PostUserHabits for application/json ContentType.
type PostUserHabitsJSONRequestBody PostUserHabitsJSONBody

// PutUserHabitsJSONRequestBody defines body for PutUserHabits for application/json ContentType.
type PutUserHabitsJSONRequestBody PutUserHabitsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить все привычки
	// (GET /habits)
	GetHabits(ctx echo.Context) error
	// Создать новую привычку
	// (POST /habits)
	PostHabits(ctx echo.Context) error
	// Обновление информации о привычке
	// (PUT /habits)
	PutHabits(ctx echo.Context) error
	// Удаление привычки по идентификатору
	// (DELETE /habits/{habitId})
	DeleteHabitsHabitId(ctx echo.Context, habitId int) error
	// Получение привычки по идентификатору
	// (GET /habits/{habitId})
	GetHabitsHabitId(ctx echo.Context, habitId int) error
	// Вход пользователя
	// (POST /login)
	PostLogin(ctx echo.Context) error
	// Регистрация нового пользователя
	// (POST /register)
	PostRegister(ctx echo.Context) error
	// Получение всех связей пользователь-привычка с датой и планами
	// (GET /user_habits)
	GetUserHabits(ctx echo.Context) error
	// Добавить привычку к пользователю
	// (POST /user_habits)
	PostUserHabits(ctx echo.Context) error
	// Изменение плана привычки у пользователя
	// (PUT /user_habits)
	PutUserHabits(ctx echo.Context) error
	// Получение ифнормации о привычках пользователей по идентификатору
	// (GET /user_habits/{userId})
	GetUserHabitsUserId(ctx echo.Context, userId int) error
	// Удаляет связь между пользователем и привычкой
	// (DELETE /user_habits/{userId}/{habitId})
	DeleteUserHabitsUserIdHabitId(ctx echo.Context, userId UserId, habitId HabitId) error
	// Возвращает информацию о конкретной привычке конкретного пользователя
	// (GET /user_habits/{userId}/{habitId})
	GetUserHabitsUserIdHabitId(ctx echo.Context, userId UserId, habitId HabitId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHabits converts echo context to params.
func (w *ServerInterfaceWrapper) GetHabits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHabits(ctx)
	return err
}

// PostHabits converts echo context to params.
func (w *ServerInterfaceWrapper) PostHabits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostHabits(ctx)
	return err
}

// PutHabits converts echo context to params.
func (w *ServerInterfaceWrapper) PutHabits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutHabits(ctx)
	return err
}

// DeleteHabitsHabitId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteHabitsHabitId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "habitId" -------------
	var habitId int

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", ctx.Param("habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter habitId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteHabitsHabitId(ctx, habitId)
	return err
}

// GetHabitsHabitId converts echo context to params.
func (w *ServerInterfaceWrapper) GetHabitsHabitId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "habitId" -------------
	var habitId int

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", ctx.Param("habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter habitId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHabitsHabitId(ctx, habitId)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// PostRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostRegister(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRegister(ctx)
	return err
}

// GetUserHabits converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserHabits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserHabits(ctx)
	return err
}

// PostUserHabits converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserHabits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUserHabits(ctx)
	return err
}

// PutUserHabits converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserHabits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutUserHabits(ctx)
	return err
}

// GetUserHabitsUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserHabitsUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserHabitsUserId(ctx, userId)
	return err
}

// DeleteUserHabitsUserIdHabitId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserHabitsUserIdHabitId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", ctx.Param("habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter habitId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserHabitsUserIdHabitId(ctx, userId, habitId)
	return err
}

// GetUserHabitsUserIdHabitId converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserHabitsUserIdHabitId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", ctx.Param("habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter habitId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserHabitsUserIdHabitId(ctx, userId, habitId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/habits", wrapper.GetHabits)
	router.POST(baseURL+"/habits", wrapper.PostHabits)
	router.PUT(baseURL+"/habits", wrapper.PutHabits)
	router.DELETE(baseURL+"/habits/:habitId", wrapper.DeleteHabitsHabitId)
	router.GET(baseURL+"/habits/:habitId", wrapper.GetHabitsHabitId)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.POST(baseURL+"/register", wrapper.PostRegister)
	router.GET(baseURL+"/user_habits", wrapper.GetUserHabits)
	router.POST(baseURL+"/user_habits", wrapper.PostUserHabits)
	router.PUT(baseURL+"/user_habits", wrapper.PutUserHabits)
	router.GET(baseURL+"/user_habits/:userId", wrapper.GetUserHabitsUserId)
	router.DELETE(baseURL+"/user_habits/:userId/:habitId", wrapper.DeleteUserHabitsUserIdHabitId)
	router.GET(baseURL+"/user_habits/:userId/:habitId", wrapper.GetUserHabitsUserIdHabitId)

}
