// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// DeleteHabitJSONBody defines parameters for DeleteHabit.
type DeleteHabitJSONBody struct {
	Id int `json:"id"`
}

// GetHabitJSONBody defines parameters for GetHabit.
type GetHabitJSONBody struct {
	Id int `json:"id"`
}

// PostHabitJSONBody defines parameters for PostHabit.
type PostHabitJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// PutHabitJSONBody defines parameters for PutHabit.
type PutHabitJSONBody struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// DeleteHabitJSONRequestBody defines body for DeleteHabit for application/json ContentType.
type DeleteHabitJSONRequestBody DeleteHabitJSONBody

// GetHabitJSONRequestBody defines body for GetHabit for application/json ContentType.
type GetHabitJSONRequestBody GetHabitJSONBody

// PostHabitJSONRequestBody defines body for PostHabit for application/json ContentType.
type PostHabitJSONRequestBody PostHabitJSONBody

// PutHabitJSONRequestBody defines body for PutHabit for application/json ContentType.
type PutHabitJSONRequestBody PutHabitJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удаление привычки по id
	// (DELETE /habit)
	DeleteHabit(ctx echo.Context) error
	// Получить привычку по id
	// (GET /habit)
	GetHabit(ctx echo.Context) error
	// Создать новую привычку
	// (POST /habit)
	PostHabit(ctx echo.Context) error
	// Обновление информации о привычке
	// (PUT /habit)
	PutHabit(ctx echo.Context) error
	// Вход пользователя
	// (POST /login)
	PostLogin(ctx echo.Context) error
	// Регистрация нового пользователя
	// (POST /register)
	PostRegister(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteHabit converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteHabit(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteHabit(ctx)
	return err
}

// GetHabit converts echo context to params.
func (w *ServerInterfaceWrapper) GetHabit(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHabit(ctx)
	return err
}

// PostHabit converts echo context to params.
func (w *ServerInterfaceWrapper) PostHabit(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostHabit(ctx)
	return err
}

// PutHabit converts echo context to params.
func (w *ServerInterfaceWrapper) PutHabit(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutHabit(ctx)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// PostRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostRegister(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRegister(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/habit", wrapper.DeleteHabit)
	router.GET(baseURL+"/habit", wrapper.GetHabit)
	router.POST(baseURL+"/habit", wrapper.PostHabit)
	router.PUT(baseURL+"/habit", wrapper.PutHabit)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.POST(baseURL+"/register", wrapper.PostRegister)

}
