/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthApi);
  }
}(this, function(expect, AuthApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthApi.HobbiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HobbiesApi', function() {
    describe('apiHabitsGet', function() {
      it('should call apiHabitsGet successfully', function(done) {
        //uncomment below and update the code to test apiHabitsGet
        //instance.apiHabitsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiHabitsHabitIdGet', function() {
      it('should call apiHabitsHabitIdGet successfully', function(done) {
        //uncomment below and update the code to test apiHabitsHabitIdGet
        //instance.apiHabitsHabitIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiHabitsHabitIdPut', function() {
      it('should call apiHabitsHabitIdPut successfully', function(done) {
        //uncomment below and update the code to test apiHabitsHabitIdPut
        //instance.apiHabitsHabitIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiHabitsPost', function() {
      it('should call apiHabitsPost successfully', function(done) {
        //uncomment below and update the code to test apiHabitsPost
        //instance.apiHabitsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
