/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ScoreHabit from '../model/ScoreHabit';

/**
* HobbiesScore service.
* @module api/HobbiesScoreApi
* @version 1.0.0
*/
export default class HobbiesScoreApi {

    /**
    * Constructs a new HobbiesScoreApi. 
    * @alias module:api/HobbiesScoreApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiHabitsHabitIdScorePost operation.
     * @callback module:api/HobbiesScoreApi~apiHabitsHabitIdScorePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Записать время, потраченное на хобби
     * @param {Number} habitId 
     * @param {module:model/ScoreHabit} scoreHabit 
     * @param {module:api/HobbiesScoreApi~apiHabitsHabitIdScorePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiHabitsHabitIdScorePost(habitId, scoreHabit, callback) {
      let postBody = scoreHabit;
      // verify the required parameter 'habitId' is set
      if (habitId === undefined || habitId === null) {
        throw new Error("Missing the required parameter 'habitId' when calling apiHabitsHabitIdScorePost");
      }
      // verify the required parameter 'scoreHabit' is set
      if (scoreHabit === undefined || scoreHabit === null) {
        throw new Error("Missing the required parameter 'scoreHabit' when calling apiHabitsHabitIdScorePost");
      }

      let pathParams = {
        'habitId': habitId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/habits/{habitId}/score', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
