/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Habit from '../model/Habit';
import HabitUpdate from '../model/HabitUpdate';
import NewHabit from '../model/NewHabit';

/**
* Hobbies service.
* @module api/HobbiesApi
* @version 1.0.0
*/
export default class HobbiesApi {

    /**
    * Constructs a new HobbiesApi. 
    * @alias module:api/HobbiesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiHabitsGet operation.
     * @callback module:api/HobbiesApi~apiHabitsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Habit>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить список хобби пользователя
     * @param {module:api/HobbiesApi~apiHabitsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Habit>}
     */
    apiHabitsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Habit];
      return this.apiClient.callApi(
        '/api/habits', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiHabitsHabitIdGet operation.
     * @callback module:api/HobbiesApi~apiHabitsHabitIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Habit} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить детали хобби
     * @param {Number} habitId 
     * @param {module:api/HobbiesApi~apiHabitsHabitIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Habit}
     */
    apiHabitsHabitIdGet(habitId, callback) {
      let postBody = null;
      // verify the required parameter 'habitId' is set
      if (habitId === undefined || habitId === null) {
        throw new Error("Missing the required parameter 'habitId' when calling apiHabitsHabitIdGet");
      }

      let pathParams = {
        'habitId': habitId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Habit;
      return this.apiClient.callApi(
        '/api/habits/{habitId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiHabitsHabitIdPut operation.
     * @callback module:api/HobbiesApi~apiHabitsHabitIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Обновить хобби
     * @param {Number} habitId 
     * @param {module:model/HabitUpdate} habitUpdate 
     * @param {module:api/HobbiesApi~apiHabitsHabitIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiHabitsHabitIdPut(habitId, habitUpdate, callback) {
      let postBody = habitUpdate;
      // verify the required parameter 'habitId' is set
      if (habitId === undefined || habitId === null) {
        throw new Error("Missing the required parameter 'habitId' when calling apiHabitsHabitIdPut");
      }
      // verify the required parameter 'habitUpdate' is set
      if (habitUpdate === undefined || habitUpdate === null) {
        throw new Error("Missing the required parameter 'habitUpdate' when calling apiHabitsHabitIdPut");
      }

      let pathParams = {
        'habitId': habitId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/habits/{habitId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiHabitsPost operation.
     * @callback module:api/HobbiesApi~apiHabitsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Habit} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создать новое хобби
     * @param {module:model/NewHabit} newHabit 
     * @param {module:api/HobbiesApi~apiHabitsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Habit}
     */
    apiHabitsPost(newHabit, jwtToken, callback) {
      let postBody = newHabit;
      // verify the required parameter 'newHabit' is set
      if (newHabit === undefined || newHabit === null) {
        throw new Error("Missing the required parameter 'newHabit' when calling apiHabitsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        Authorization: `Bearer ${jwtToken}`,
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Habit;
      return this.apiClient.callApi(
        '/api/habits', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
