/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HabitStatisticResponse from '../model/HabitStatisticResponse';
import HabitStatisticTotalResponse from '../model/HabitStatisticTotalResponse';
import StatisticGroupBy from '../model/StatisticGroupBy';

/**
* HobbiesStatistic service.
* @module api/HobbiesStatisticApi
* @version 1.0.0
*/
export default class HobbiesStatisticApi {

    /**
    * Constructs a new HobbiesStatisticApi. 
    * @alias module:api/HobbiesStatisticApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiHabitsHabitIdStatisticGet operation.
     * @callback module:api/HobbiesStatisticApi~apiHabitsHabitIdStatisticGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HabitStatisticResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение статустики
     * @param {Number} habitId 
     * @param {Date} dateFrom 
     * @param {Date} dateTo 
     * @param {module:model/StatisticGroupBy} groupBy 
     * @param {module:api/HobbiesStatisticApi~apiHabitsHabitIdStatisticGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HabitStatisticResponse}
     */
    apiHabitsHabitIdStatisticGet(habitId, dateFrom, dateTo, groupBy, callback) {
      let postBody = null;
      // verify the required parameter 'habitId' is set
      if (habitId === undefined || habitId === null) {
        throw new Error("Missing the required parameter 'habitId' when calling apiHabitsHabitIdStatisticGet");
      }
      // verify the required parameter 'dateFrom' is set
      if (dateFrom === undefined || dateFrom === null) {
        throw new Error("Missing the required parameter 'dateFrom' when calling apiHabitsHabitIdStatisticGet");
      }
      // verify the required parameter 'dateTo' is set
      if (dateTo === undefined || dateTo === null) {
        throw new Error("Missing the required parameter 'dateTo' when calling apiHabitsHabitIdStatisticGet");
      }
      // verify the required parameter 'groupBy' is set
      if (groupBy === undefined || groupBy === null) {
        throw new Error("Missing the required parameter 'groupBy' when calling apiHabitsHabitIdStatisticGet");
      }

      let pathParams = {
        'habitId': habitId
      };
      let queryParams = {
        'date-from': dateFrom,
        'date-to': dateTo,
        'group-by': groupBy
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HabitStatisticResponse;
      return this.apiClient.callApi(
        '/api/habits/{habitId}/statistic', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiHabitsHabitIdStatisticTotalGet operation.
     * @callback module:api/HobbiesStatisticApi~apiHabitsHabitIdStatisticTotalGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HabitStatisticTotalResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение статустики
     * @param {Number} habitId 
     * @param {module:api/HobbiesStatisticApi~apiHabitsHabitIdStatisticTotalGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HabitStatisticTotalResponse}
     */
    apiHabitsHabitIdStatisticTotalGet(habitId, callback) {
      let postBody = null;
      // verify the required parameter 'habitId' is set
      if (habitId === undefined || habitId === null) {
        throw new Error("Missing the required parameter 'habitId' when calling apiHabitsHabitIdStatisticTotalGet");
      }

      let pathParams = {
        'habitId': habitId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HabitStatisticTotalResponse;
      return this.apiClient.callApi(
        '/api/habits/{habitId}/statistic/total', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
