/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import UserProfile from '../model/UserProfile';
import UserProfileUpdate from '../model/UserProfileUpdate';

/**
* Users service.
* @module api/UsersApi
* @version 1.0.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiUsersAvatarPost operation.
     * @callback module:api/UsersApi~apiUsersAvatarPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Загрузить аватар
     * @param {Object} opts Optional parameters
     * @param {File} [file] 
     * @param {module:api/UsersApi~apiUsersAvatarPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiUsersAvatarPost(jwtToken, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        Authorization: `Bearer ${jwtToken}`,
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/users/avatar', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiUsersProfileGet operation.
     * @callback module:api/UsersApi~apiUsersProfileGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserProfile} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить профиль пользователя
     * @param {module:api/UsersApi~apiUsersProfileGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserProfile}
     */
    apiUsersProfileGet(jwtToken, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        Authorization: `Bearer ${jwtToken}`,
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserProfile;
      return this.apiClient.callApi(
        '/api/users/profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiUsersProfilePut operation.
     * @callback module:api/UsersApi~apiUsersProfilePutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Обновить профиль пользователя
     * @param {module:model/UserProfileUpdate} userProfileUpdate 
     * @param {module:api/UsersApi~apiUsersProfilePutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiUsersProfilePut(userProfileUpdate, callback) {
      let postBody = userProfileUpdate;
      // verify the required parameter 'userProfileUpdate' is set
      if (userProfileUpdate === undefined || userProfileUpdate === null) {
        throw new Error("Missing the required parameter 'userProfileUpdate' when calling apiUsersProfilePut");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/users/profile', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
