/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HabitStatisticResponsePeriodInner model module.
 * @module model/HabitStatisticResponsePeriodInner
 * @version 1.0.0
 */
class HabitStatisticResponsePeriodInner {
    /**
     * Constructs a new <code>HabitStatisticResponsePeriodInner</code>.
     * @alias module:model/HabitStatisticResponsePeriodInner
     */
    constructor() { 
        
        HabitStatisticResponsePeriodInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HabitStatisticResponsePeriodInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HabitStatisticResponsePeriodInner} obj Optional instance to populate.
     * @return {module:model/HabitStatisticResponsePeriodInner} The populated <code>HabitStatisticResponsePeriodInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HabitStatisticResponsePeriodInner();

            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HabitStatisticResponsePeriodInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HabitStatisticResponsePeriodInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['interval'] && !(typeof data['interval'] === 'string' || data['interval'] instanceof String)) {
            throw new Error("Expected the field `interval` to be a primitive type in the JSON string but got " + data['interval']);
        }

        return true;
    }


}



/**
 * тут приходит в зависимости от типа, условно если мы выбрали день, то приходят дни недели, если месяц, то месяца, аналогично с годами
 * @member {String} interval
 */
HabitStatisticResponsePeriodInner.prototype['interval'] = undefined;

/**
 * тут приходит значение в зависимости от типа
 * @member {Number} value
 */
HabitStatisticResponsePeriodInner.prototype['value'] = undefined;






export default HabitStatisticResponsePeriodInner;

