/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Plan from './Plan';

/**
 * The Habit model module.
 * @module model/Habit
 * @version 1.0.0
 */
class Habit {
    /**
     * Constructs a new <code>Habit</code>.
     * @alias module:model/Habit
     */
    constructor() { 
        
        Habit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Habit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Habit} obj Optional instance to populate.
     * @return {module:model/Habit} The populated <code>Habit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Habit();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('currentPlan')) {
                obj['currentPlan'] = Plan.constructFromObject(data['currentPlan']);
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = ApiClient.convertToType(data['notifications'], 'Boolean');
            }
            if (data.hasOwnProperty('todayValue')) {
                obj['todayValue'] = ApiClient.convertToType(data['todayValue'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Habit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Habit</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `currentPlan`
        if (data['currentPlan']) { // data not null
          Plan.validateJSON(data['currentPlan']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Habit.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Habit.prototype['name'] = undefined;

/**
 * @member {Date} startDate
 */
Habit.prototype['startDate'] = undefined;

/**
 * @member {module:model/Plan} currentPlan
 */
Habit.prototype['currentPlan'] = undefined;

/**
 * @member {Boolean} notifications
 */
Habit.prototype['notifications'] = undefined;

/**
 * today in sec
 * @member {Number} todayValue
 */
Habit.prototype['todayValue'] = undefined;






export default Habit;

