/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlanUnit from './PlanUnit';

/**
 * The HabitStatisticTotalResponse model module.
 * @module model/HabitStatisticTotalResponse
 * @version 1.0.0
 */
class HabitStatisticTotalResponse {
    /**
     * Constructs a new <code>HabitStatisticTotalResponse</code>.
     * @alias module:model/HabitStatisticTotalResponse
     */
    constructor() { 
        
        HabitStatisticTotalResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HabitStatisticTotalResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HabitStatisticTotalResponse} obj Optional instance to populate.
     * @return {module:model/HabitStatisticTotalResponse} The populated <code>HabitStatisticTotalResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HabitStatisticTotalResponse();

            if (data.hasOwnProperty('planUnit')) {
                obj['planUnit'] = PlanUnit.constructFromObject(data['planUnit']);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('averagePerDay')) {
                obj['averagePerDay'] = ApiClient.convertToType(data['averagePerDay'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HabitStatisticTotalResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HabitStatisticTotalResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/PlanUnit} planUnit
 */
HabitStatisticTotalResponse.prototype['planUnit'] = undefined;

/**
 * @member {Number} total
 */
HabitStatisticTotalResponse.prototype['total'] = undefined;

/**
 * @member {Number} averagePerDay
 */
HabitStatisticTotalResponse.prototype['averagePerDay'] = undefined;






export default HabitStatisticTotalResponse;

