/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HabitStatisticResponsePeriodInner from './HabitStatisticResponsePeriodInner';
import PlanUnit from './PlanUnit';
import StatisticGroupBy from './StatisticGroupBy';

/**
 * The HabitStatisticResponse model module.
 * @module model/HabitStatisticResponse
 * @version 1.0.0
 */
class HabitStatisticResponse {
    /**
     * Constructs a new <code>HabitStatisticResponse</code>.
     * @alias module:model/HabitStatisticResponse
     */
    constructor() { 
        
        HabitStatisticResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HabitStatisticResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HabitStatisticResponse} obj Optional instance to populate.
     * @return {module:model/HabitStatisticResponse} The populated <code>HabitStatisticResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HabitStatisticResponse();

            if (data.hasOwnProperty('groupBy')) {
                obj['groupBy'] = StatisticGroupBy.constructFromObject(data['groupBy']);
            }
            if (data.hasOwnProperty('planUnit')) {
                obj['planUnit'] = PlanUnit.constructFromObject(data['planUnit']);
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], [HabitStatisticResponsePeriodInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HabitStatisticResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HabitStatisticResponse</code>.
     */
    static validateJSON(data) {
        if (data['period']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['period'])) {
                throw new Error("Expected the field `period` to be an array in the JSON data but got " + data['period']);
            }
            // validate the optional field `period` (array)
            for (const item of data['period']) {
                HabitStatisticResponsePeriodInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/StatisticGroupBy} groupBy
 */
HabitStatisticResponse.prototype['groupBy'] = undefined;

/**
 * @member {module:model/PlanUnit} planUnit
 */
HabitStatisticResponse.prototype['planUnit'] = undefined;

/**
 * @member {Array.<module:model/HabitStatisticResponsePeriodInner>} period
 */
HabitStatisticResponse.prototype['period'] = undefined;






export default HabitStatisticResponse;

