/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Plan from './Plan';

/**
 * The NewHabit model module.
 * @module model/NewHabit
 * @version 1.0.0
 */
class NewHabit {
    /**
     * Constructs a new <code>NewHabit</code>.
     * @alias module:model/NewHabit
     * @param name {String} 
     * @param plan {module:model/Plan} 
     */
    constructor(name, plan) { 
        
        NewHabit.initialize(this, name, plan);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, plan) { 
        obj['name'] = name;
        obj['plan'] = plan;
    }

    /**
     * Constructs a <code>NewHabit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewHabit} obj Optional instance to populate.
     * @return {module:model/NewHabit} The populated <code>NewHabit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewHabit();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('plan')) {
                obj['plan'] = Plan.constructFromObject(data['plan']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = ApiClient.convertToType(data['notifications'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewHabit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewHabit</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NewHabit.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `plan`
        if (data['plan']) { // data not null
          Plan.validateJSON(data['plan']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

NewHabit.RequiredProperties = ["name", "plan"];

/**
 * @member {String} name
 */
NewHabit.prototype['name'] = undefined;

/**
 * @member {module:model/Plan} plan
 */
NewHabit.prototype['plan'] = undefined;

/**
 * @member {String} description
 */
NewHabit.prototype['description'] = undefined;

/**
 * @member {Boolean} notifications
 */
NewHabit.prototype['notifications'] = undefined;






export default NewHabit;

