/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlanUnit from './PlanUnit';

/**
 * The Plan model module.
 * @module model/Plan
 * @version 1.0.0
 */
class Plan {
    /**
     * Constructs a new <code>Plan</code>.
     * @alias module:model/Plan
     */
    constructor() { 
        
        Plan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Plan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Plan} obj Optional instance to populate.
     * @return {module:model/Plan} The populated <code>Plan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Plan();

            if (data.hasOwnProperty('planUnit')) {
                obj['planUnit'] = PlanUnit.constructFromObject(data['planUnit']);
            }
            if (data.hasOwnProperty('goal')) {
                obj['goal'] = ApiClient.convertToType(data['goal'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Plan</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Plan</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/PlanUnit} planUnit
 */
Plan.prototype['planUnit'] = undefined;

/**
 * тут крч мы передаем значение в зависимости от плана, в минимальных единицах измерения, (метры, секунды, разы)
 * @member {Number} goal
 */
Plan.prototype['goal'] = undefined;






export default Plan;

