/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PlanUnit.
* @enum {}
* @readonly
*/
export default class PlanUnit {
    
        /**
         * value: "distance"
         * @const
         */
        "distance" = "distance";

    
        /**
         * value: "time"
         * @const
         */
        "time" = "time";

    
        /**
         * value: "count"
         * @const
         */
        "count" = "count";

    

    /**
    * Returns a <code>PlanUnit</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PlanUnit} The enum <code>PlanUnit</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

