/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScoreHabit model module.
 * @module model/ScoreHabit
 * @version 1.0.0
 */
class ScoreHabit {
    /**
     * Constructs a new <code>ScoreHabit</code>.
     * @alias module:model/ScoreHabit
     */
    constructor() { 
        
        ScoreHabit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScoreHabit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScoreHabit} obj Optional instance to populate.
     * @return {module:model/ScoreHabit} The populated <code>ScoreHabit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScoreHabit();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScoreHabit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScoreHabit</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Date} date
 */
ScoreHabit.prototype['date'] = undefined;

/**
 * тут крч мы передаем значение в минимальных единицах измерения, (метры, секунды, разы)
 * @member {Number} value
 */
ScoreHabit.prototype['value'] = undefined;






export default ScoreHabit;

