/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class StatisticGroupBy.
* @enum {}
* @readonly
*/
export default class StatisticGroupBy {
    
        /**
         * value: "day"
         * @const
         */
        "day" = "day";

    
        /**
         * value: "month"
         * @const
         */
        "month" = "month";

    
        /**
         * value: "year"
         * @const
         */
        "year" = "year";

    

    /**
    * Returns a <code>StatisticGroupBy</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/StatisticGroupBy} The enum <code>StatisticGroupBy</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

