/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthApi);
  }
}(this, function(expect, AuthApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthApi.ApiAuthRegisterPost200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiAuthRegisterPost200Response', function() {
    it('should create an instance of ApiAuthRegisterPost200Response', function() {
      // uncomment below and update the code to test ApiAuthRegisterPost200Response
      //var instance = new AuthApi.ApiAuthRegisterPost200Response();
      //expect(instance).to.be.a(AuthApi.ApiAuthRegisterPost200Response);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new AuthApi.ApiAuthRegisterPost200Response();
      //expect(instance).to.be();
    });

  });

}));
