/**
 * Auth API
 * API для регистрации и входа пользователей с использованием JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiAuthRegisterPost200Response from './model/ApiAuthRegisterPost200Response';
import Habit from './model/Habit';
import HabitStatisticResponse from './model/HabitStatisticResponse';
import HabitStatisticResponsePeriodInner from './model/HabitStatisticResponsePeriodInner';
import HabitStatisticTotalResponse from './model/HabitStatisticTotalResponse';
import HabitUpdate from './model/HabitUpdate';
import LoginRequest from './model/LoginRequest';
import LoginResponse from './model/LoginResponse';
import NewHabit from './model/NewHabit';
import Plan from './model/Plan';
import PlanUnit from './model/PlanUnit';
import RegisterRequest from './model/RegisterRequest';
import ScoreHabit from './model/ScoreHabit';
import StatisticGroupBy from './model/StatisticGroupBy';
import UserProfile from './model/UserProfile';
import UserProfileUpdate from './model/UserProfileUpdate';
import AuthApi from './api/AuthApi';
import HobbiesApi from './api/HobbiesApi';
import HobbiesScoreApi from './api/HobbiesScoreApi';
import HobbiesStatisticApi from './api/HobbiesStatisticApi';
import UsersApi from './api/UsersApi';


/**
* API для регистрации и входа пользователей с использованием JWT.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AuthApi = require('index'); // See note below*.
* var xxxSvc = new AuthApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AuthApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AuthApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AuthApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiAuthRegisterPost200Response model constructor.
     * @property {module:model/ApiAuthRegisterPost200Response}
     */
    ApiAuthRegisterPost200Response,

    /**
     * The Habit model constructor.
     * @property {module:model/Habit}
     */
    Habit,

    /**
     * The HabitStatisticResponse model constructor.
     * @property {module:model/HabitStatisticResponse}
     */
    HabitStatisticResponse,

    /**
     * The HabitStatisticResponsePeriodInner model constructor.
     * @property {module:model/HabitStatisticResponsePeriodInner}
     */
    HabitStatisticResponsePeriodInner,

    /**
     * The HabitStatisticTotalResponse model constructor.
     * @property {module:model/HabitStatisticTotalResponse}
     */
    HabitStatisticTotalResponse,

    /**
     * The HabitUpdate model constructor.
     * @property {module:model/HabitUpdate}
     */
    HabitUpdate,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginResponse model constructor.
     * @property {module:model/LoginResponse}
     */
    LoginResponse,

    /**
     * The NewHabit model constructor.
     * @property {module:model/NewHabit}
     */
    NewHabit,

    /**
     * The Plan model constructor.
     * @property {module:model/Plan}
     */
    Plan,

    /**
     * The PlanUnit model constructor.
     * @property {module:model/PlanUnit}
     */
    PlanUnit,

    /**
     * The RegisterRequest model constructor.
     * @property {module:model/RegisterRequest}
     */
    RegisterRequest,

    /**
     * The ScoreHabit model constructor.
     * @property {module:model/ScoreHabit}
     */
    ScoreHabit,

    /**
     * The StatisticGroupBy model constructor.
     * @property {module:model/StatisticGroupBy}
     */
    StatisticGroupBy,

    /**
     * The UserProfile model constructor.
     * @property {module:model/UserProfile}
     */
    UserProfile,

    /**
     * The UserProfileUpdate model constructor.
     * @property {module:model/UserProfileUpdate}
     */
    UserProfileUpdate,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The HobbiesApi service constructor.
    * @property {module:api/HobbiesApi}
    */
    HobbiesApi,

    /**
    * The HobbiesScoreApi service constructor.
    * @property {module:api/HobbiesScoreApi}
    */
    HobbiesScoreApi,

    /**
    * The HobbiesStatisticApi service constructor.
    * @property {module:api/HobbiesStatisticApi}
    */
    HobbiesStatisticApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
