openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API для регистрации и входа пользователей с использованием JWT

servers:
  - url: http://localhost:8080
    description: Production server

paths:
  /register:
    post:
      summary: Регистрация нового пользователя
      description: Регистрирует нового пользователя и возвращает статус "ok"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user123
                password:
                  type: string
                  example: password123
              required:
                - username
                - password
      responses:
        '200':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '400':
          description: Неверные данные для регистрации
        '409':
          description: Пользователь с таким именем уже существует

  /login:
    post:
      summary: Вход пользователя
      description: Аутентифицирует пользователя и возвращает JWT токен
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user123
                password:
                  type: string
                  example: password123
              required:
                - username
                - password
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT токен для аутентификации
        '400':
          description: Неверные данные для входа
        '401':
          description: Неверный логин или пароль
  /habits:
    post:
      summary: Создать новую привычку
      description: Создает новую привычку для текущего пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                habit_name:
                  type: string
                  example: running
                description:
                  type: string
                  example: smth interesting
      responses:
        '200':
          description: Успешное добавление
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '409':
          description: Такая привычка уже есть, выберите ее из списка
        '500':
          description: Что-то с соединением
        '400':
          description: Плохой запрос
    get:
      summary: Получить все привычки
      description: Возвращает все привычки
      responses:
        '200':
          description: Успешный ответ со списком привычек
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/habits"

        '404':
          description: Ничего не найдно

    put:
      summary: Обновление информации о привычке
      description: Обновляет информацию о привычке
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/habit"
      responses:
        '200':
          description: Информация о привычке успешно изменена
        '404':
          description: Такой привычки не существует
        '500':
          description: Что-то с соединением
        '400':
          description: Плохой запрос
  /habits/{habitId}:
    get:
      summary: Получение привычки по идентификатору
      parameters:
        - name: habitId
          in: path
          required: true
          description: Идентификатор привычки
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Успешный ответ с одной привычкой
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/habit"

        '404':
          description: Привычка не найдена
    delete:
      summary: Удаление привычки по идентификатору
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Привычка успешно удаленна
        '404':
          description: Привычка не найдена
  /user_habits:
    post:
      summary: Добавить привычку к пользователю
      description: Добавляет в user_habit связь привычки и пользователя с датой и планом
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                habit_name:
                  type: string
                  example: running
                description:
                  type: string
                  example: smth interesting
                user_id:
                  type: integer
                  example: 1
                start_date:
                  type: string
                  format: date
                  example: "2025-02-01"
                current_plan:
                  type: integer
                  example: 30
              required:
                - habit_name
                - user_id
                - start_date
                - current_plan

      responses:
        '200':
          description: Успешное добавление
        '404':
          description: Не найден такой пользователь
    get:
      summary: Получение всех связей пользователь-привычка с датой и планами
      responses:
        '200':
          description: успешный ответ со списком связей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userHabit"
        '404':
          description: Данные не найдены
    put:
      summary: Изменение плана привычки у пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                habit_id:
                  type: integer
                  example: 1
                current_plan:
                  type: integer
                  example: 1
              required:
                - user_id
                - habit_id
                - current_plan
      responses:
        '200':
          description: Успешно изменен план
        '404':
          description: Пользователь не найден
  /user_habits/{userId}:
    get:
      summary: Получение ифнормации о привычках пользователей по идентификатору
      parameters:
        - name: userId
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Списко успешно получен
          content:
           application/json:
             schema:
               $ref: "#/components/schemas/userHabits"
        '404':
          description: Пользователь не найден
  /user_habits/{userId}/{habitId}:
    get:
      summary: Возвращает информацию о конкретной привычке конкретного пользователя
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/habitId"
      responses:
        '200':
          description: Данные получены успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userHabit"
    delete:
      summary: Удаляет связь между пользователем и привычкой
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/habitId"
      responses:
        '200':
          description: Успешное удаление
        '404':
          description: Не найдена связь

























components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    userId:
      name: userId
      in: path
      required: true
      description: идентификатор пользователя
      schema:
        type: integer
        example: 1
    habitId:
      name: habitId
      in: path
      required: true
      description: идентификатор привычки
      schema:
        type: integer
        example: 1
  schemas:
    userHabit:
      type: object
      properties:
        user_id:
          type: integer
          example: 2
        habit_id:
          type: integer
          example: 3
        start_date:
          type: string
          format: date
          example: "2025-02-01"
        current_plan:
          type: integer
          example: 30
    userHabits:
      type: array
      items:
        $ref: "#/components/schemas/userHabit"
    habit:
      type: object
      properties:
        habit_id:
          type: integer
          example: 1
        habit_name:
          type: string
          example: running
        description:
          type: string
          example: something interesting
      required:
        - habit_id
    habits:
      type: array
      items:
        $ref: "#/components/schemas/habit"









security:
  - BearerAuth: []